### ISSUE TITLE
another 'just me being so curious'

### ISSUE THREAD

**Issue by memoowi** [numen111104/nide_tix#1]
So... i noticed something that i've never use before.. 
> a widget called `PageView` in your folder path [`lib/widgets/scrool_image.dart`](https://github.com/numen111104/nide_tix/blob/master/lib/widgets/scrool_image.dart). If you may share you knowledge and tell me what does it look like and what it's use for?

> I also noticed that it got method builder innit

Thank you in advance

**Comment by numen111104** [comment]
Alright, so it's just a feature I whipped up. I was scratching my head on how to make a carousel from scratch, but hey, ended up using the carousel_slider package. BIG THANKS FOR THE SHOUTOUT!
